require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VendasController do

  # This should return the minimal set of attributes required to create a valid
  # Venda. As you add validations to Venda, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VendasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vendas as @vendas" do
      venda = Venda.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vendas).should eq([venda])
    end
  end

  describe "GET show" do
    it "assigns the requested venda as @venda" do
      venda = Venda.create! valid_attributes
      get :show, {:id => venda.to_param}, valid_session
      assigns(:venda).should eq(venda)
    end
  end

  describe "GET new" do
    it "assigns a new venda as @venda" do
      get :new, {}, valid_session
      assigns(:venda).should be_a_new(Venda)
    end
  end

  describe "GET edit" do
    it "assigns the requested venda as @venda" do
      venda = Venda.create! valid_attributes
      get :edit, {:id => venda.to_param}, valid_session
      assigns(:venda).should eq(venda)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Venda" do
        expect {
          post :create, {:venda => valid_attributes}, valid_session
        }.to change(Venda, :count).by(1)
      end

      it "assigns a newly created venda as @venda" do
        post :create, {:venda => valid_attributes}, valid_session
        assigns(:venda).should be_a(Venda)
        assigns(:venda).should be_persisted
      end

      it "redirects to the created venda" do
        post :create, {:venda => valid_attributes}, valid_session
        response.should redirect_to(Venda.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved venda as @venda" do
        # Trigger the behavior that occurs when invalid params are submitted
        Venda.any_instance.stub(:save).and_return(false)
        post :create, {:venda => {}}, valid_session
        assigns(:venda).should be_a_new(Venda)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Venda.any_instance.stub(:save).and_return(false)
        post :create, {:venda => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested venda" do
        venda = Venda.create! valid_attributes
        # Assuming there are no other vendas in the database, this
        # specifies that the Venda created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Venda.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => venda.to_param, :venda => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested venda as @venda" do
        venda = Venda.create! valid_attributes
        put :update, {:id => venda.to_param, :venda => valid_attributes}, valid_session
        assigns(:venda).should eq(venda)
      end

      it "redirects to the venda" do
        venda = Venda.create! valid_attributes
        put :update, {:id => venda.to_param, :venda => valid_attributes}, valid_session
        response.should redirect_to(venda)
      end
    end

    describe "with invalid params" do
      it "assigns the venda as @venda" do
        venda = Venda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Venda.any_instance.stub(:save).and_return(false)
        put :update, {:id => venda.to_param, :venda => {}}, valid_session
        assigns(:venda).should eq(venda)
      end

      it "re-renders the 'edit' template" do
        venda = Venda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Venda.any_instance.stub(:save).and_return(false)
        put :update, {:id => venda.to_param, :venda => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested venda" do
      venda = Venda.create! valid_attributes
      expect {
        delete :destroy, {:id => venda.to_param}, valid_session
      }.to change(Venda, :count).by(-1)
    end

    it "redirects to the vendas list" do
      venda = Venda.create! valid_attributes
      delete :destroy, {:id => venda.to_param}, valid_session
      response.should redirect_to(vendas_url)
    end
  end

end
